name: myarts
description: A myarts project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  get_it: ^7.2.0
  retrofit: ^2.0.1
  dio: ^4.0.0
  logger: ^1.1.0
  equatable: ^2.0.3
  meta: ^1.3.0
  json_annotation: ^4.0.1
  connectivity: ^3.0.6
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1
  flutter_spinkit: ^5.1.0
  hive: ^2.0.4
  easy_localization: ^3.0.0
  sizer: ^2.0.13
  dartz: ^0.10.0
  pull_to_refresh: ^2.0.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: any


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
    - assets/images/
    - assets/images/launcher_icons/
  fonts:
    - family: Soleil
      fonts:
        - asset: assets/fonts/soleil/Soleil-Bold.otf
          weight: 700
        - asset: assets/fonts/soleil/Soleil-Semibold.otf
          weight: 600
        - asset: assets/fonts/soleil/Soleil-Regular.otf
          weight: 400


